spring.datasource.url: jdbc:h2:file:./camunda-h2-database
camunda.bpm.admin-user:
  id: demo
  password: demo
camunda:
  bpm:
    job-executor-acquire-by-priority: true
    job-execution:
      core-pool-size: 6
logging:
  level:
    ROOT: DEBUG
